//
//  AddToDoTaskWorker.swift
//  EjemploCleanSwift
//
//  Created by Federico Valerin on 6/6/17.
//  Copyright (c) 2017 Federico Valerin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class AddToDoTaskWorker{
    // MARK: Business Logic
    
    func doSomeWork(){
        // NOTE: Do the work
    }
}
