//
//  ToDoTasksListConfigurator.swift
//  EjemploCleanSwift
//
//  Created by Federico Valerin on 6/6/17.
//  Copyright (c) 2017 Federico Valerin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension ToDoTasksListViewController: ToDoTasksListPresenterOutput{
    func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?){
        router.passDataToNextScene(segue: segue)
    }
}

extension ToDoTasksListInteractor: ToDoTasksListViewControllerOutput{
}

extension ToDoTasksListPresenter: ToDoTasksListInteractorOutput{
}

class ToDoTasksListConfigurator{
    // MARK: Object lifecycle
    
    class var sharedInstance: ToDoTasksListConfigurator{
        struct Static {
            static let instance =  ToDoTasksListConfigurator()
        }
        return Static.instance
    }
    
    // MARK: Configuration
    
    func configure(viewController: ToDoTasksListViewController){
        let router = ToDoTasksListRouter()
        router.viewController = viewController
        
        let presenter = ToDoTasksListPresenter()
        presenter.output = viewController
        
        let interactor = ToDoTasksListInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
