//
//  ToDoTasksListModels.swift
//  EjemploCleanSwift
//
//  Created by Federico Valerin on 6/6/17.
//  Copyright (c) 2017 Federico Valerin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct ToDoTasksList{
    
    struct TestInformation {
        struct Request{
            var numberText: String
        }
        
        struct Response{
            var number: Int
        }
        
        struct ViewModel{
            var numberText: String
        }
    }
    
    struct clsTareas {
        var text : String
        var counter: Int
    }
    
    struct TaskModelCell {
        var text:String
        var counter:String
    }
    
    struct clsDataSource {
        struct Request{
            
        }
    
        struct Response{
            var arrTareas: [clsTareas] = []
        }
    
        struct ViewModel {
            //var nada : Int
            var arrTareasViewModel: [clsTareas] = []
//            func init( parrTareas : [clsTareas]){
//                arrTareasViewModel = parrTareas
//            }
        }
    }
}

