//
//  ToDoTasksListWorker.swift
//  EjemploCleanSwift
//
//  Created by Federico Valerin on 6/6/17.
//  Copyright (c) 2017 Federico Valerin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class ToDoTasksListWorker{
    // MARK: Business Logic
    
    var arrTareas : [ToDoTasksList.clsTareas]?
    
    func Multiply(number:String)-> Int {
        return Int(number)! * 2
    }
    
    func CrearTareas() -> [ToDoTasksList.clsTareas] {
        
        let a = ToDoTasksList.clsTareas(text: "tarea 1", counter: 1)
        let b = ToDoTasksList.clsTareas(text: "tarea 2", counter: 2)
        let c = ToDoTasksList.clsTareas(text: "tarea 3", counter: 3)
        return [a, b, c]
    }
    
    func ObtenerTareas() -> [ToDoTasksList.clsTareas] {
        if arrTareas == nil {
            arrTareas = CrearTareas()
        }
        return arrTareas!
    }
    
    
}
